language: node_js
node_js:
 - "8.9.1"
 - "lts/*"

cache:
 directories:
   - "node_modules"
   - "webpack.js.org"

git:
  submodules:
    false

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - git clone --depth=1 https://github.com/webpack/webpack.js.org.git

script: npm run build