language: node_js
node_js:
 - "8.9.1"
 - "lts/*"

cache:
 directories:
   - "node_modules"
git:
  submodules:
    false
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "$GITHUB_NAME"
  - git config --local user.email "$GITHUB_EMAIL"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: "$$GITHUB_TOKEN"
  file: "webpack.tgz"
  skip_cleanup: true
before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - rm -rf ./webpack.js.org && git clone --depth=1 https://github.com/webpack/webpack.js.org.git

install:
  - npm install --global yarn
  - sudo pip install proselint
script: npm run build