language: node_js
node_js:
 - "8.9.1"
 - "lts/*"

cache:
 directories:
   - "node_modules"
   - "webpack.js.org"
before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
script: npm run build